services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    image: hcmute-student-topic-management:local

    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5000:5000"

    volumes:
      - report_storage:/app/storage/reports

    restart: unless-stopped

volumes:
  report_storage: