-- HCMUTE Student Topic Management
--
-- Seed data is now created by the protected application endpoint instead of
-- being maintained as a second copy of the seed rules in SQL:
--
--   POST /api/admin/seed
--
-- The endpoint truncates every application table first, then recreates the
-- local roles, permissions, test accounts and sample Student Profile in one
-- application flow. It requires an authenticated ADMIN account.
--
-- Run database/1.ddl.sql for a new database, or database/4.update-ddl.sql for
-- an existing database, start the application, then call the endpoint.
-- This file is intentionally kept as a migration-era pointer so future
-- changes do not create SQL/API seed drift.
